--- #This playbook downloads and installs the latest version of Plex
- name: Update Plex
  hosts:  192.168.2.79

 tasks:
 - name:   Install a .deb package from the internet.
   apt:
     deb: https://downloads.plex.tv/plex-media-server-new/1.15.6.1079-78232c603/debian/plexmediaserver_1.15.6.1079-78232c603_amd64.deb