--- #This playbook downloads and installs the latest version of Plex with alerts from Pushbullet
- name: Update Plex with alerts
  hosts:  your Plex Server IP here
  become: true

# Sends a push notification to phone letting me know Plex update is about to start
  tasks:  
    - pushbullet: 
        api_key: Your API key here
        device: "The device NAME you wish to send the push notification to as seen on Pushbullets main page"
        title: "Starting to Update Plex"
        body:  "The Update to Plex is about to begin"
# Sends a push notification to phone letting me know Plex is updating
    - pushbullet: 
        api_key: Your API key here
        device: "The device NAME you wish to send the push notification to as seen on Pushbullets main page"
        title: "Starting to Update Plex"
        body:  "Plex is in the process of updating"
# Installs the Plex deb package        
    - name: Install a .deb package from the internet.
      apt:
       deb: https://downloads.plex.tv/plex-media-server-new/1.16.6.1592-b9d49bdb7/debian/plexmediaserver_1.16.6.1592-b9d49bdb7_amd64.deb
# Sends a push notification to phone letting me know Plex has updated 
    - pushbullet: 
        api_key: Your API key here
        device: "The device NAME you wish to send the push notification to as seen on Pushbullets main page"
        title: "Plex Updated"
        body:  "Plex has finished updating"
