--- #This playbook downloads and installs the latest version of Plex
- name: Update Plex
  hosts:  192.168.2.79
  become: true

  tasks:
  - name: Install a .deb package from the internet.
    apt:
       deb: https://downloads.plex.tv/plex-media-server-new/1.15.8.1198-eadbcbb45/debian/plexmediaserver_1.15.8.1198-eadbcbb45_amd64.deb
